### ISSUE TITLE
Add option "no-inherit" to requirements and svcs

### ISSUE THREAD

**Issue by lfvbarcus** [Luftfartsverket/reqstool-client#24]
## Summary

Some requirements and/or svcs are never to be included by a microservice. 

## Proposal

Make it possible for a system to specify that a requirement/svc or group of requirements/svcs shall only exist for the particular system.

* property name: TBD (inherit, local..)

Example:

```
requirements:
  "group1": 
    description: ""
    inherit: <bool>
    requirements:
    - id: # alphanumerical
      title: # text
      significance: # was level # shall, should, may # https://www.rfc-editor.org/rfc/rfc2119
      description: # text
      rationale: # text
      category: # [Business, User Interface, System Interface, Performance, IT Security, Information Security, Reliability, Operational]
      inherit: <bool>
      references: # links, source
        - requirement_ids: [REQ123] # links to another requirement in this document
        - sources: [FSB] # FSB, SAF, SWAL
        - requirement_ids: [REQ123] # links to another requirement in this document
          sources: [FSB] # FSB, SAF, SWAL
      revision: # requirement added from revision number, e.g. 1.0.2
```
