### ISSUE TITLE
Add groups to requirements and potentially svcs

### ISSUE THREAD

**Issue by lfvbarcus** [Luftfartsverket/reqstool-client#25]
## Summary

There is a need to be able to group requirements and potentially svcs. Especially, when there are many.

## Proposal

Make it possible to group and for groups to have a short description.

```
requirements:
  "group1": 
    description: ""
    requirements:

    - id: # alphanumerical
      title: # text
      significance: # was level # shall, should, may # https://www.rfc-editor.org/rfc/rfc2119
      description: # text
      rationale: # text
      category: # [Business, User Interface, System Interface, Performance, IT Security, Information Security, Reliability, Operational]
      references: # links, source
        - requirement_ids: [REQ123] # links to another requirement in this document
        - sources: [FSB] # FSB, SAF, SWAL
        - requirement_ids: [REQ123] # links to another requirement in this document
          sources: [FSB] # FSB, SAF, SWAL
      revision: # requirement added from revision number, e.g. 1.0.2
```
