### ISSUE TITLE
Requirement references throws error if requirement_ids are not defined

### ISSUE THREAD

**Issue by lfvbarcus** [Luftfartsverket/reqstool-client#42]
If you are using the references field when you are defining a requirement, the schema allows you to either specifiy references like this

```
    references:
      - requirement_ids:
          - "REQ 0825"
        sources:
          - "ext-101"
```

or like this:

```
    references:
      - sources:
          [
            "E08-EXAMPLE: 3.1.2.1.1 SUB_RESP",
            "E08-EXAMPLE: 3.1.2.1",
          ]
```

if you are writing your references like in example 2, the the report command will throw an error since it expects a value in the requirement_ids field.

The questions is what is correct? Should you be able to define sources without requirement_ids? In that case, the logic in report.py (line 178)  needs to change, otherwise, the schema needs to be updated to not allow sources to be defined without requirements_ids
