### ISSUE TITLE
Investigate multiple MVRs for the same SVC

### ISSUE THREAD

**Issue by lfvJonas** [Luftfartsverket/reqstool-client#72]
### Description

Say we have a SVC to manually verify a XSD file. When we first do the MVR it fails because there are some fields that are missing. We fix the errors and do a second MVR that passes. Using the current version of reqstool (0.4.3) the requirement associated with the SVC does not pass as implemented and tested since it has one passed and one failed MVR. 

```
╒═════════════════════╤═══════════╤══════════════════╤══════════════════╤═══════════════╕
│         URN         │  Req Id   │  Implementation  │  Automated Test  │  Manual Test  │
╞═════════════════════╪═══════════╪══════════════════╪══════════════════╪═══════════════╡
│        sys001       │  req001   │  Implemented     │       N/A        │     T2 P1 F1  │
├─────────────────────┼───────────┼──────────────────┼──────────────────┼───────────────┤
```

How should this be handled?

**Comment by jimisola** [comment]
There needs to be some sort of ordering if we are to support this. In your use-case was it 2 MVRs in the same file?

I'm thinking that perhaps you could reuse the MVR id but write it as multiple YAML documents in the same file.
We probably do not allow it when parsing but it would make sense to do it.

```
--- # 2026-01-01
results:
  - id: MVR_001
    svc_ids: ["SVC_021"]
    pass: false
  # ...
--- # 2026-01-02
results:
  - id: MVR_001
    svc_ids: ["SVC_021"]
    pass: true
  # ...
```
