### ISSUE TITLE
Unable to import SVCs if cases are empty

### ISSUE THREAD

**Issue by lfvJonas** [Luftfartsverket/reqstool-client#74]
## Issue Title

Unable to import SVCs if cases are empty

### Description

If I want to import SVC from another system then I cant do it with an empty cases list in the current project. The example below does not work. This is a desirable feature.

```
filters:
  sys001:
    svc_ids:
      includes:
        - svc134
        - svc140
        - svc142
        - svc148
        - svc149
        - svc150
        - svc151
        - svc152
        - svc153

cases: []

```
