### ISSUE TITLE
Report command does not filter requirements

### ISSUE THREAD

**Issue by lfvJonas** [luftfartsverket/reqstool-client#84]
# Description
I have a mircoservice that imports three requirement from a system (REQ_001, REQ_002, REQ_003). I have filters in my microservice that filters out some of the requirements from the system ex:

```
# yaml-language-server: $schema=https://schemas.lfv.se/sysdev/requirements-tool/v1/requirements.schema.json
metadata:
  urn: ms001
  title: Test
  variant: microservice

imports:
  git:
    - branch: main
      env_token: <TOKEN>
      url: <URL>
      path: <PATH>

filters:
  sys001:
    requirement_ids:
      excludes:
        - "REQ_001"
        - "REQ_003"
```

When running the Status command I get the correct view status with only one requirement: 
```
sys001:REQ_002
```
But when running the report command to get an asciidoc file I get a summary of all requirements

```
TOTAL STATISTICS
Imported
Requirement REQ_001
Requirement REQ_002
Requirement REQ_003
```
